import os
import zipfile
import logging

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def create_release_build(root_dir: str):
    dist_dir = os.path.join(root_dir, "dist")
    os.makedirs(dist_dir, exist_ok=True)
    
    zip_path = os.path.join(dist_dir, "AIManager_Release.zip")
    logging.info(f"Assembling pristine release build: {zip_path}")

    # Files and folders to strictly ignore when packaging
    ignore_dirs = {
        "bin", "packages", "dist", ".git", "__pycache__", "cache", ".gemini",
        ".venv", ".pytest_cache", ".tests", "node_modules", ".github"
    }
    ignore_files = {
        "metadata.sqlite", "build.py", "AIManager_Release.zip",
        ".coverage", "test_results.txt", "merged_walkthroughs.md",
        "merged_walkthroughs.txt", "pending_work.md", "collect_docs.py",
        "requirements-qa.txt"
    }
    
    # We will explicitly add Global_Vault subdirectories manually as empty stubs
    ignore_dirs.add("Global_Vault")
    
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        # Walk and add core source files
        for root, dirs, files in os.walk(root_dir):
            # Prune ignored directories in-place so os.walk ignores them
            dirs[:] = [d for d in dirs if d not in ignore_dirs]
            
            for file in files:
                if file in ignore_files or file.endswith(".pyc"):
                    continue
                    
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, root_dir)
                zipf.write(file_path, arcname)
                
        # Manually add the Global Vault skeleton layout
        vault_folders = [
            "Global_Vault/checkpoints/",
            "Global_Vault/loras/",
            "Global_Vault/vaes/",
            "Global_Vault/controlnet/",
            "Global_Vault/unet/",
            "Global_Vault/clip/",
            "Global_Vault/upscaler/",
            "Global_Vault/motion/",
        ]
        
        for folder in vault_folders:
            zipInfo = zipfile.ZipInfo(folder)
            zipf.writestr(zipInfo, "")
            
        # Add the .manager_ignore token
        zipf.writestr("Global_Vault/.manager_ignore", "Autogenerated Vault Marker")
            
    logging.info("Build payload compiled successfully.")
    
if __name__ == "__main__":
    rood_path = os.path.dirname(os.path.abspath(__file__))
    create_release_build(rood_path)
